name: CD Pipeline (to Hugging Face Space)

on:
  workflow_run:
    workflows: ["CI Pipeline"]  
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Git LFS
        run: |
          git lfs install
      
      - name: Build deploy folder
        run: |
          mkdir -p deploy

          cp app.py deploy/
          cp requirements.txt deploy/
          cp README.md deploy/
          cp .gitattributes deploy/
          cp .gitignore deploy/

          cp -r models deploy/
          cp -r data/clean deploy/data

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "bouiflanemaryam@outlook.fr"
          git config --global user.name "Maryam-Bouiflane"

          rm -rf hf-space

          git clone https://maryamb123:${HF_TOKEN}@huggingface.co/spaces/maryamb123/p4-classification-app hf-space

          rsync -av deploy/ hf-space/ --exclude .git

          cd hf-space
          git add .
          git commit -m "Auto deploy from CI/CD" || echo "No changes to commit"
          git push