name: CI-CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-train-deploy:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10 

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tests
        run: poetry run pytest

      - name: Clean old models
        run: rm -rf models

      - name: Run training (creates model + threshold)
        run: poetry run python main.py

      # - name: Commit trained model to GitHub
      #   run: |
      #     git config --global user.email "bouiflanemaryam@outlook.fr"
      #     git config --global user.name "Maryam-Bouiflane"

      #     git add models/

      #     git commit -m "Update trained model and threshold" || echo "No changes to commit"

      #     git push origin main

      - name: Build deploy folder
        run: |
          mkdir deploy
          mkdir -p deploy/data
          mkdir -p deploy/models
          mkdir -p deploy/src

          cp app.py deploy/
          cp requirements.txt deploy/
          cp README.md deploy/
          cp Dockerfile deploy/
          cp .gitignore deploy/
          cp .gitattributes deploy/
          cp -r data/clean/. deploy/data
          cp -r models deploy/
          cp src/schemas.py deploy/src/

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "bouiflanemaryam@outlook.fr"
          git config --global user.name "Maryam-Bouiflane"

          rm -rf hf-space

          git clone https://maryamb123:${HF_TOKEN}@huggingface.co/spaces/maryamb123/p4-classification-app hf-space

          rsync -av --delete --exclude .git deploy/ hf-space/

          cd hf-space
          git add .
          git commit -m "Auto deploy from CI/CD" || echo "No changes to commit"
          git push