name: CI-CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tests
        run: poetry run pytest

      - name: Clean old artifacts
        run: rm -rf models

      - name: Run training (creates model + threshold)
        run: poetry run python main.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ml-artifacts
          path: models/

  deploy:
    needs: test-and-train
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare deploy folder
        run: |
          mkdir -p deploy/models
          mkdir -p deploy/data

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ml-artifacts
          path: deploy/models/

      - name: Build deploy folder
        run: |
          cp app.py deploy/
          cp requirements.txt deploy/
          cp README.md deploy/
          cp Dockerfile deploy/
          cp .gitignore deploy/
          cp .gitattributes deploy/
          cp -r data/clean deploy/data

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "bouiflanemaryam@outlook.fr"
          git config --global user.name "Maryam-Bouiflane"

          rm -rf hf-space

          git clone https://maryamb123:${HF_TOKEN}@huggingface.co/spaces/maryamb123/p4-classification-app hf-space

          rsync -av --delete --exclude .git deploy/ hf-space/

          cd hf-space
          git add .
          git commit -m "Auto deploy from CI/CD" || echo "No changes to commit"
          git push